### ISSUE TITLE
Adjust the TestRunner to work in an automated way

### ISSUE THREAD

**Issue by ovanr** [ovanr/TCP-Test#3]
Currently TestRunner works by loading the script in an interactive environment and then manually adding commands to the `sutQueue` and the `serverQueue`. 
Now that we are doing automated testing, this step needs to be automated, thus the TestRunner must load the test cases from a definition file and run them automatically (while taking care that for each test case the Test Server and the SUT are reinitialised).

Goal of this issue is to automate the TestRunner

**Comment by Oberacda** [comment]
Development will be done on the [automate_test_runner](https://github.com/ovanr/TCP-Test/tree/automate_test_runner) branch.
